name: Monorepo CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, web, api, payments, legacy, api-java, api-ruby, api-python]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (for api-gateway, web)
        if: matrix.service == 'api-gateway' || matrix.service == 'web'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/${{ matrix.service }}/package-lock.json

      - name: Set up .NET (for api)
        if: matrix.service == 'api'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Set up Go (for payments)
        if: matrix.service == 'payments'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Python (for api-python)
        if: matrix.service == 'api-python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Java (for api-java)
        if: matrix.service == 'api-java'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Ruby (for api-ruby)
        if: matrix.service == 'api-ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'

      - name: Install dependencies and test
        run: |
          set -e  # Stop script on first failure

          echo "Running tests for service: ${{ matrix.service }}"
          case "${{ matrix.service }}" in
            api-gateway|web)
              cd apps/${{ matrix.service }}
              echo "Checking package-lock.json..."
              if [ ! -f package-lock.json ]; then
                echo "❌ Error: Missing package-lock.json in apps/${{ matrix.service }}"
                exit 1
              fi
              npm ci || npm install  # fallback if npm ci fails
              npm run test || echo "⚠️ npm test failed"
              npm run lint || echo "⚠️ npm lint failed"
              ;;

            api)
              cd apps/DotNetBoilerplate
              dotnet restore
              dotnet test
              ;;

            payments)
              cd apps/${{ matrix.service }}
              go mod download
              go test ./...
              ;;

            api-python)
              cd apps/django-boilerplate
              pip install -r requirements.txt
              python -m pytest
              ;;

            api-java)
              cd apps/spring-boilerplate
              chmod +x mvnw
              ./mvnw test
              ;;

            api-ruby)
              cd apps/ruby-rails-boilerplate

              echo "📦 Installing dependencies..."
              sudo apt-get update && sudo apt-get install -y \
                libvips libvips-dev \
                build-essential libpq-dev libsqlite3-dev zlib1g-dev nodejs yarn

              bundle install --jobs 4 --retry 3 --verbose

              echo "🗃️ Preparing test database..."
              RAILS_ENV=test DISABLE_BOOTSNAP=1 bundle exec rails db:prepare || true

              echo "🧪 Running Rails tests..."
              RAILS_ENV=test DISABLE_BOOTSNAP=1 bundle exec rails test || (echo '❌ Rails test failed' && exit 1)

              echo "📄 Dumping test log (if exists)..."
              if [ -f log/test.log ]; then cat log/test.log; else echo 'log/test.log not found'; fi

              echo "📁 Log directory listing:"
              ls -la log || echo "log/ directory not found"
              ;;

            legacy)
              echo "Legacy PHP service - skipping tests"
              ;;
          esac


  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service: [api-gateway, web, api, payments, legacy, api-java, api-ruby, api-python]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.service }}.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/adidas-${{ matrix.service }}:latest
            ${{ env.DOCKER_USERNAME }}/adidas-${{ matrix.service }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy Spring service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Deploy Rails service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_RAILS }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Deploy DotNet service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_DOTNET }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Vercel (Frontend)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--cwd apps/web --debug'
          github-comment: false
